package epc

import (
	"os"
	"path/filepath"
	"testing"
)

// TestGoldenAgainstSegno cross-validates the payload builder against fixtures
// generated by segno's reference implementation (scripts/gen_segno_fixtures.py;
// keep the inputs here in sync with the CASES dict there). Amounts avoid
// trailing zeros: segno strips them while epcii keeps two decimals — both are
// EPC069-12-conform, so the cases are chosen where the normalizations agree.
func TestGoldenAgainstSegno(t *testing.T) {
	cases := map[string]Payment{
		"basic": {
			Name:   "ACME GmbH",
			IBAN:   "DE02120300000000202051",
			Amount: "12.34",
			Text:   "Invoice RE-2026-001",
		},
		"umlauts": {
			Name:   "Müller & Söhne GmbH",
			IBAN:   "DE02120300000000202051",
			Amount: "580.55",
			Text:   "Rechnung RE-4a7f — Überweisung",
		},
		"bic_purpose": {
			Name:    "François D'Alsace S.A.",
			IBAN:    "FR1420041010050500013M02606",
			BIC:     "BNPAFRPP",
			Amount:  "12.34",
			Purpose: "GDDS",
			Text:    "Client:Marie Louise La Lune",
		},
		"reference": {
			Name:   "ACME GmbH",
			IBAN:   "DE02120300000000202051",
			Amount: "99.99",
			Ref:    "RF18539007547034",
		},
		"min_amount": {
			Name:   "ACME GmbH",
			IBAN:   "DE02120300000000202051",
			Amount: "0.01",
			Text:   "x",
		},
		"max_amount": {
			Name:   "ACME GmbH",
			IBAN:   "DE02120300000000202051",
			Amount: "999999999.99",
			Text:   "max",
		},
	}

	for name, p := range cases {
		want, err := os.ReadFile(filepath.Join("testdata", "segno_"+name+".golden"))
		if err != nil {
			t.Fatalf("%s: %v", name, err)
		}
		got, err := p.Payload()
		if err != nil {
			t.Errorf("%s: %v", name, err)
			continue
		}
		if got != string(want) {
			t.Errorf("%s: payload differs from segno:\ngot:  %q\nwant: %q", name, got, want)
		}
	}
}
