// This test is original epcii code, not derived from piglig/go-qr.

package qr

import (
	"bufio"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"strings"
	"testing"
)

// fixtureVariants mirrors fixtureVariants in scripts/qrfixtures/main.go.
var fixtureVariants = []string{"a", "lcg"}

// fixturePayload mirrors fixturePayload in scripts/qrfixtures/main.go. Both
// copies must stay identical.
func fixturePayload(variant string, n int) []byte {
	const header = "BCD\n002\n1\nSCT\n"
	if n <= len(header) {
		return []byte(header[:n])
	}
	b := make([]byte, n)
	copy(b, header)
	x := uint32(20260903)
	for i := len(header); i < n; i++ {
		switch variant {
		case "a":
			b[i] = 'A'
		case "lcg":
			x = x*1664525 + 1013904223
			b[i] = byte(x >> 24)
		default:
			panic("unknown fixture variant " + variant)
		}
	}
	return b
}

// fingerprint hashes the module matrix row-major, one byte per module,
// exactly like scripts/qrfixtures does for the upstream encoder.
func fingerprint(c *Code) string {
	h := sha256.New()
	size := c.Size()
	row := make([]byte, size)
	for y := 0; y < size; y++ {
		for x := 0; x < size; x++ {
			row[x] = 0
			if c.Module(x, y) {
				row[x] = 1
			}
		}
		h.Write(row)
	}
	return hex.EncodeToString(h.Sum(nil))
}

// TestMatrixFingerprints is the in-tree equivalence proof against upstream
// piglig/go-qr: for every payload length 0..331 and filler variant the chosen
// version and the full module matrix (mask choice, function patterns,
// padding, ECC) must match the fixture generated by scripts/qrfixtures. The
// round-trip decoder tolerates ECC-repairable damage; this gate does not.
func TestMatrixFingerprints(t *testing.T) {
	f, err := os.Open("testdata/matrix_fingerprints.txt")
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()

	const lengths = 332 // 0..331 inclusive, per variant
	seen := map[string]int{}
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := sc.Text()
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		var variant, want string
		var n, version int
		if _, err := fmt.Sscanf(line, "%s %d %d %s", &variant, &n, &version, &want); err != nil {
			t.Fatalf("fixture line %q: %v", line, err)
		}
		if n != seen[variant] {
			t.Fatalf("variant %q: fixture lengths must be contiguous from 0: got %d, want %d", variant, n, seen[variant])
		}
		seen[variant]++

		code, err := EncodeM(fixturePayload(variant, n))
		if err != nil {
			t.Fatalf("%s %d: %v", variant, n, err)
		}
		if code.Version() != version {
			t.Errorf("%s %d: version %d, upstream chose %d", variant, n, code.Version(), version)
			continue
		}
		if got := fingerprint(code); got != want {
			t.Errorf("%s %d (version %d): matrix diverged from piglig/go-qr — "+
				"mask choice, function patterns, padding or ECC changed; see CONTRIBUTING "+
				"(\"Touching internal/qr\") before touching the fixture", variant, n, version)
		}
	}
	if err := sc.Err(); err != nil {
		t.Fatal(err)
	}
	for _, variant := range fixtureVariants {
		if seen[variant] != lengths {
			t.Fatalf("variant %q: fixture has %d entries, want %d (lengths 0..331)", variant, seen[variant], lengths)
		}
	}
	if len(seen) != len(fixtureVariants) {
		t.Fatalf("fixture carries %d variants, want %d", len(seen), len(fixtureVariants))
	}
}
