// This test is original epcii code, not derived from piglig/go-qr.

package qr

import (
	"bufio"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"strings"
	"testing"
)

// fixturePayload mirrors fixturePayload in scripts/qrfixtures/main.go. Both
// copies must stay identical.
func fixturePayload(n int) []byte {
	const header = "BCD\n002\n1\nSCT\n"
	if n <= len(header) {
		return []byte(header[:n])
	}
	b := make([]byte, n)
	copy(b, header)
	for i := len(header); i < n; i++ {
		b[i] = 'A'
	}
	return b
}

// fingerprint hashes the module matrix row-major, one byte per module,
// exactly like scripts/qrfixtures does for the upstream encoder.
func fingerprint(c *Code) string {
	h := sha256.New()
	size := c.Size()
	row := make([]byte, size)
	for y := 0; y < size; y++ {
		for x := 0; x < size; x++ {
			row[x] = 0
			if c.Module(x, y) {
				row[x] = 1
			}
		}
		h.Write(row)
	}
	return hex.EncodeToString(h.Sum(nil))
}

// TestMatrixFingerprints is the in-tree equivalence proof against upstream
// piglig/go-qr: for every payload length 0..331 the chosen version and the
// full module matrix (mask choice, function patterns, padding, ECC) must
// match the fixture generated by scripts/qrfixtures. The round-trip decoder
// tolerates ECC-repairable damage; this gate does not.
func TestMatrixFingerprints(t *testing.T) {
	f, err := os.Open("testdata/matrix_fingerprints.txt")
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()

	const wantLines = 332 // lengths 0..331 inclusive
	seen := 0
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := sc.Text()
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		var n, version int
		var want string
		if _, err := fmt.Sscanf(line, "%d %d %s", &n, &version, &want); err != nil {
			t.Fatalf("fixture line %q: %v", line, err)
		}
		if n != seen {
			t.Fatalf("fixture lengths must be contiguous from 0: got %d, want %d", n, seen)
		}
		seen++

		code, err := EncodeM(fixturePayload(n))
		if err != nil {
			t.Fatalf("length %d: %v", n, err)
		}
		if code.Version() != version {
			t.Errorf("length %d: version %d, upstream chose %d", n, code.Version(), version)
			continue
		}
		if got := fingerprint(code); got != want {
			t.Errorf("length %d (version %d): matrix diverged from piglig/go-qr — "+
				"mask choice, function patterns, padding or ECC changed; see CONTRIBUTING "+
				"(\"Touching internal/qr\") before touching the fixture", n, version)
		}
	}
	if err := sc.Err(); err != nil {
		t.Fatal(err)
	}
	if seen != wantLines {
		t.Fatalf("fixture has %d entries, want %d (lengths 0..331)", seen, wantLines)
	}
}
