// epcii web: form → globalThis.epcii.generate (Go/WASM) → inline SVG.
//
// Zero-storage contract: this file never touches a storage API, cookies, the
// history or the address bar (scripts/web-smoke.mjs greps for that). The only
// state that can leave the page is a share link the user asks for, and it
// lives in the #fragment.
'use strict';

const FIELDS = ['name', 'iban', 'amount', 'text', 'ref', 'bic', 'purpose', 'info'];

// Mirrors payloadFieldNames in main.go (printDetails).
const PAYLOAD_FIELDS = [
  'service tag', 'version', 'charset', 'identification',
  'bic', 'name', 'iban', 'amount', 'purpose', 'ref', 'text', 'info',
];

const STR = {
  en: {
    tagline: 'EPC QR code (GiroCode) for SEPA credit transfers — generated in your browser, nothing leaves it.',
    name: 'Beneficiary name',
    amount: 'Amount (EUR)',
    amount_ph: 'e.g. 12.50 or 12,50',
    text: 'Remittance text',
    more_fields: 'More fields (reference, BIC, purpose code, note to the payer)',
    ref: 'Creditor reference',
    ref_ph: 'RF… (excludes remittance text)',
    bic_ph: 'only for accounts outside the EEA',
    purpose: 'Purpose code',
    purpose_ph: 'e.g. SALA, 4 letters',
    info: 'Note shown to the payer',
    language: 'Language',
    loading: 'Loading generator…',
    load_failed: 'The generator could not be loaded. Your browser needs WebAssembly.',
    empty: 'Enter at least a name and an IBAN.',
    bad_link: 'This link was made by a newer version of the page and was not loaded.',
    bad_svg: 'The generator returned an image this page cannot show.',
    dl_svg: 'Download SVG',
    dl_png: 'Download PNG',
    copy_link: 'Copy link',
    copied: 'Link copied',
    copy_failed: 'Copying failed — the link is:',
    share: 'Share',
    share_text: 'Payment QR code',
    details: 'Encoded payload',
    details_head: (n, v, s) => `encoded GiroCode payload (${n} bytes, QR version ${v}, ${s}x${s} modules):`,
    privacy: 'No server, no cookies, no storage: the code is generated by this page alone. A shared link carries the payment data only in its #fragment, which browsers never send to any server.',
    more: 'How this works',
  },
  de: {
    tagline: 'EPC-QR-Code (GiroCode) für SEPA-Überweisungen — erzeugt im Browser, nichts verlässt ihn.',
    name: 'Name der Empfängerin / des Empfängers',
    amount: 'Betrag (EUR)',
    amount_ph: 'z. B. 12,50 oder 12.50',
    text: 'Verwendungszweck',
    more_fields: 'Weitere Felder (Referenz, BIC, Verwendungscode, Hinweis an die zahlende Person)',
    ref: 'Strukturierte Referenz',
    ref_ph: 'RF… (schließt Verwendungszweck aus)',
    bic_ph: 'nur für Konten außerhalb des EWR',
    purpose: 'Verwendungscode',
    purpose_ph: 'z. B. SALA, 4 Zeichen',
    info: 'Hinweis, der der zahlenden Person angezeigt wird',
    language: 'Sprache',
    loading: 'Generator wird geladen…',
    load_failed: 'Der Generator konnte nicht geladen werden. Der Browser braucht WebAssembly.',
    empty: 'Mindestens Name und IBAN eingeben.',
    bad_link: 'Dieser Link stammt von einer neueren Version der Seite und wurde nicht geladen.',
    bad_svg: 'Der Generator hat ein Bild geliefert, das diese Seite nicht anzeigen kann.',
    dl_svg: 'SVG herunterladen',
    dl_png: 'PNG herunterladen',
    copy_link: 'Link kopieren',
    copied: 'Link kopiert',
    copy_failed: 'Kopieren fehlgeschlagen — der Link lautet:',
    share: 'Teilen',
    share_text: 'Zahlungs-QR-Code',
    details: 'Kodierte Nutzdaten',
    details_head: (n, v, s) => `kodierte GiroCode-Nutzdaten (${n} Bytes, QR-Version ${v}, ${s}x${s} Module):`,
    privacy: 'Kein Server, keine Cookies, kein Speicher: der Code entsteht allein auf dieser Seite. Ein geteilter Link trägt die Zahlungsdaten nur im #Fragment, das Browser nie an einen Server senden.',
    more: 'So funktioniert es',
  },
};

const $ = (id) => document.getElementById(id);
const els = {
  fields: $('fields'), status: $('status'), error: $('error'), qr: $('qr'),
  actions: $('actions'), detailsBox: $('details-box'), details: $('details'),
  dlSvg: $('dl-svg'), dlPng: $('dl-png'), copyLink: $('copy-link'), share: $('share'),
  version: $('version'),
};

let lang = 'en';
let last = null; // last successful generate() result
let statusKey = 'loading'; // STR key shown in #status while the wasm is not usable
let statusDetail = ''; // appended to the load_failed message
let ready = false; // wasm loaded and globalThis.epcii registered

function showStatus() {
  els.status.textContent = STR[lang][statusKey] + statusDetail;
}

function applyLang(code) {
  lang = STR[code] ? code : 'en';
  document.documentElement.lang = lang;
  const t = STR[lang];
  for (const el of document.querySelectorAll('[data-i18n]')) {
    const s = t[el.dataset.i18n];
    if (typeof s === 'string') el.textContent = s;
  }
  for (const el of document.querySelectorAll('[data-i18n-placeholder]')) {
    el.placeholder = t[el.dataset.i18nPlaceholder];
  }
  $('lang-en').setAttribute('aria-pressed', String(lang === 'en'));
  $('lang-de').setAttribute('aria-pressed', String(lang === 'de'));
  $('lang-nav').setAttribute('aria-label', t.language);
  if (!ready) showStatus();
  else render(); // details header and the page's own messages are localized
}

function readForm() {
  const fields = {};
  for (const k of FIELDS) fields[k] = $(k).value;
  return fields;
}

function showError(msg) {
  els.error.textContent = msg;
  els.error.hidden = !msg;
}

function showDetails(res) {
  const bytes = new TextEncoder().encode(res.payload).length;
  const lines = [STR[lang].details_head(bytes, res.version, res.size)];
  res.payload.split('\n').forEach((v, i) => {
    lines.push('  ' + (PAYLOAD_FIELDS[i] + ':').padEnd(15) + ' ' + (v === '' ? '(empty)' : v));
  });
  els.details.textContent = lines.join('\n');
}

function render() {
  const fields = readForm();
  const empty = FIELDS.every((k) => fields[k].trim() === '');
  let res;
  try {
    res = empty ? { error: STR[lang].empty } : globalThis.epcii.generate(fields);
  } catch (e) {
    // Fail closed: a stale QR next to new field values must never survive.
    res = { error: String(e && e.message ? e.message : e) };
  }
  let svg = null;
  if (!res.error) {
    // The SVG is parsed as XML and inserted as a node, never assigned as an
    // HTML string. render.SVG emits geometry only, but that invariant lives
    // in another module; a string sink here would turn any change there
    // into script running in this page's origin.
    svg = new DOMParser().parseFromString(res.svg, 'image/svg+xml').documentElement;
    if (svg.nodeName !== 'svg' || svg.querySelector('parsererror')) {
      res = { error: STR[lang].bad_svg };
    }
  }
  if (res.error) {
    last = null;
    showError(res.error);
    els.qr.hidden = true;
    els.actions.hidden = true;
    els.detailsBox.hidden = true;
    return;
  }
  last = res;
  showError('');
  els.qr.replaceChildren(document.importNode(svg, true));
  els.qr.hidden = false;
  showDetails(res);
  els.detailsBox.hidden = false;
  els.actions.hidden = false;
}

let timer = 0;
function scheduleRender() {
  clearTimeout(timer);
  timer = setTimeout(render, 150);
}

// --- share link: #v=1&name=…  (fragment only; never written to the address bar)

function shareParams() {
  const p = new URLSearchParams();
  p.set('v', LINK_VERSION);
  const fields = readForm();
  for (const k of FIELDS) if (fields[k] !== '') p.set(k, fields[k]);
  return p;
}

function shareURL() {
  return location.origin + location.pathname + '#' + shareParams().toString();
}

const LINK_VERSION = '1';

// loadFragment fills the form from a share link. Returns true when fields
// were filled; a link from a newer format version is refused, not guessed.
function loadFragment() {
  const raw = location.hash.slice(1);
  if (!raw) return false;
  const p = new URLSearchParams(raw);
  if ((p.get('v') || LINK_VERSION) !== LINK_VERSION) {
    showError(STR[lang].bad_link);
    return false;
  }
  let any = false;
  for (const k of FIELDS) {
    const v = p.get(k);
    if (v !== null) {
      $(k).value = v;
      any = true;
      if (v !== '' && $('more').contains($(k))) $('more').open = true;
    }
  }
  return any;
}

// Typed characters outside the amount alphabet are dropped before they land;
// a paste is left alone so the validator can name what is wrong with it.
function guardAmountInput(e) {
  if (e.inputType === 'insertText' && e.data && /[^0-9 .,€]/.test(e.data)) e.preventDefault();
}

// --- downloads

// The stem comes from the payload that was actually encoded, never from the
// form: rendering is debounced, so the IBAN field may already be ahead of
// `last`, and the file must not be named after an IBAN it does not contain.
// Payload line 7 is the IBAN (see PAYLOAD_FIELDS).
function fileStem() {
  const iban = last ? last.payload.split('\n')[6] || '' : '';
  return /^[A-Z0-9]+$/.test(iban) ? 'epc-' + iban : 'epc';
}

function download(blob, name) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = name;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function svgBlob() { return new Blob([last.svg], { type: 'image/svg+xml' }); }
function pngBlob() { return new Blob([last.png], { type: 'image/png' }); }

function flash(button, text) {
  button.textContent = text;
  button.disabled = true;
  // Restore from the i18n table, not from a captured string: the language
  // may have changed in the meantime.
  setTimeout(() => { button.textContent = STR[lang][button.dataset.i18n]; button.disabled = false; }, 1500);
}

async function copyLink() {
  const url = shareURL();
  try {
    await navigator.clipboard.writeText(url);
    flash(els.copyLink, STR[lang].copied);
  } catch {
    // Clipboard denied (e.g. no user gesture, permissions): show it instead.
    showError(STR[lang].copy_failed + ' ' + url);
  }
}

async function share() {
  const data = { title: 'epcii', text: STR[lang].share_text, url: shareURL() };
  const file = new File([svgBlob()], fileStem() + '.svg', { type: 'image/svg+xml' });
  if (navigator.canShare && navigator.canShare({ files: [file] })) data.files = [file];
  try {
    await navigator.share(data);
  } catch (e) {
    if (e && e.name !== 'AbortError') showError(String(e.message || e));
  }
}

// --- boot

async function loadWasm() {
  const go = new Go();
  let result;
  try {
    result = await WebAssembly.instantiateStreaming(fetch('epcii.wasm'), go.importObject);
  } catch {
    // Wrong MIME type or no streaming support: fall back to a plain buffer.
    const buf = await (await fetch('epcii.wasm')).arrayBuffer();
    result = await WebAssembly.instantiate(buf, go.importObject);
  }
  go.run(result.instance); // resolves only when the Go program exits; it never does
  for (let i = 0; i < 100 && !globalThis.epcii; i++) {
    await new Promise((r) => setTimeout(r, 10));
  }
  if (!globalThis.epcii) throw new Error('epcii global not registered');
}

async function main() {
  applyLang((navigator.language || 'en').toLowerCase().startsWith('de') ? 'de' : 'en');
  $('lang-en').addEventListener('click', () => applyLang('en'));
  $('lang-de').addEventListener('click', () => applyLang('de'));

  try {
    await loadWasm();
  } catch (e) {
    statusKey = 'load_failed';
    statusDetail = ' (' + (e && e.message ? e.message : e) + ')';
    showStatus();
    return;
  }
  ready = true;
  els.status.hidden = true;
  els.version.textContent = globalThis.epcii.version;
  els.fields.disabled = false;

  $('form').addEventListener('input', scheduleRender);
  $('amount').addEventListener('beforeinput', guardAmountInput);
  $('form').addEventListener('submit', (e) => { e.preventDefault(); render(); });
  els.dlSvg.addEventListener('click', () => download(svgBlob(), fileStem() + '.svg'));
  els.dlPng.addEventListener('click', () => download(pngBlob(), fileStem() + '.png'));
  els.copyLink.addEventListener('click', copyLink);
  if (navigator.share) {
    els.share.hidden = false;
    els.share.addEventListener('click', share);
  }

  if (loadFragment()) render();
  else $('name').focus();
}

main();
